# Generated by Django 4.0.6 on 2022-07-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nghang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngname', models.CharField(max_length=250)),
                ('ngicon', models.ImageField(upload_to='img01/')),
            ],
        ),
    ]
