# Generated by Django 4.0.6 on 2022-07-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0002_alter_nghang_options_nghang_ngid_alter_nghang_ngicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nghang',
            name='ngID',
        ),
        migrations.AlterField(
            model_name='product',
            name='nghang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_nghang', to='nghang.nghang', verbose_name='Ngành hàng'),
        ),
    ]
