# Generated by Django 4.0.6 on 2022-07-20 17:18

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0003_remove_nghang_ngid_alter_product_nghang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prcontent',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Nội dung'),
        ),
    ]
