# Generated by Django 4.0.6 on 2022-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0004_alter_product_prcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prcontent',
            field=models.TextField(verbose_name='Nội dung'),
        ),
    ]
