# Generated by Django 4.0.6 on 2022-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0005_alter_product_prcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incontent', models.TextField(verbose_name='Nội dung giới thiệu')),
                ('inname', models.CharField(max_length=100, verbose_name='TPHC')),
            ],
            options={
                'verbose_name': 'Giới Thiệu',
                'verbose_name_plural': 'Giới Thiệu',
            },
        ),
    ]
