# Generated by Django 4.0.6 on 2022-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0006_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='inname',
        ),
        migrations.AddField(
            model_name='product',
            name='pSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
