# Generated by Django 4.0.6 on 2022-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0007_remove_intro_inname_product_pslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pSlug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='score',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('banchay', 'Bán chạy'), ('moive', 'Mới về')], max_length=10, null=True),
        ),
    ]
