# Generated by Django 4.0.6 on 2022-07-30 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.ImageField(upload_to='imgProduct/', verbose_name='Ảnh sản phẩm')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_product', to='nghang.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
            },
        ),
    ]
