# Generated by Django 4.0.6 on 2022-07-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0010_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Ảnh chi tiết sản phẩm', 'verbose_name_plural': 'Ảnh chi tiết sản phẩm'},
        ),
        migrations.AddField(
            model_name='intro',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='intro',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='imgname',
            field=models.ImageField(upload_to='imgProduct/', verbose_name='Ảnh chi tiết sản phẩm'),
        ),
    ]
