# Generated by Django 4.0.6 on 2022-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0011_alter_productimage_options_intro_address_intro_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='mymap',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Map'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
