# Generated by Django 4.0.6 on 2022-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0013_news_alter_intro_mymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
