# Generated by Django 4.0.6 on 2022-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0015_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='nghang',
            name='ngicon',
            field=models.ImageField(upload_to='icon/', verbose_name='Icon'),
        ),
    ]
