# Generated by Django 4.0.6 on 2022-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0016_alter_news_date_alter_nghang_ngicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='imgPost/', verbose_name='Ảnh bài viết'),
        ),
    ]
