# Generated by Django 4.0.6 on 2022-07-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0017_news_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Tên đường dẫn'),
        ),
    ]
