# Generated by Django 4.0.6 on 2022-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghang', '0018_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ads',
            field=models.CharField(blank=True, choices=[('chon', 'Chọn'), ('khongchon', 'Không Chọn')], max_length=10, null=True, verbose_name='Chọn làm quảng cáo'),
        ),
    ]
